<?php
/**
 * ScheduledMessageResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  winsms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WinSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace winsms\Models;

use \ArrayAccess;
use \winsms\ObjectSerializer;

/**
 * ScheduledMessageResponse Class Doc Comment
 *
 * @category Class
 * @package  winsms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduledMessageResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'scheduledMessageResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'timeStamp' => 'string',
        'version' => 'string',
        'statusCode' => 'int',
        'resultsOffset' => 'int',
        'resultsLimit' => 'int',
        'resultsTotalAvailable' => 'int',
        'scheduledMessages' => '\winsms\Models\ScheduledMessage[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'timeStamp' => null,
        'version' => null,
        'statusCode' => null,
        'resultsOffset' => null,
        'resultsLimit' => null,
        'resultsTotalAvailable' => null,
        'scheduledMessages' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timeStamp' => 'timeStamp',
        'version' => 'version',
        'statusCode' => 'statusCode',
        'resultsOffset' => 'resultsOffset',
        'resultsLimit' => 'resultsLimit',
        'resultsTotalAvailable' => 'resultsTotalAvailable',
        'scheduledMessages' => 'scheduledMessages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timeStamp' => 'setTimeStamp',
        'version' => 'setVersion',
        'statusCode' => 'setStatusCode',
        'resultsOffset' => 'setResultsOffset',
        'resultsLimit' => 'setResultsLimit',
        'resultsTotalAvailable' => 'setResultsTotalAvailable',
        'scheduledMessages' => 'setScheduledMessages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timeStamp' => 'getTimeStamp',
        'version' => 'getVersion',
        'statusCode' => 'getStatusCode',
        'resultsOffset' => 'getResultsOffset',
        'resultsLimit' => 'getResultsLimit',
        'resultsTotalAvailable' => 'getResultsTotalAvailable',
        'scheduledMessages' => 'getScheduledMessages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['timeStamp'] = isset($data['timeStamp']) ? $data['timeStamp'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['statusCode'] = isset($data['statusCode']) ? $data['statusCode'] : null;
        $this->container['resultsOffset'] = isset($data['resultsOffset']) ? $data['resultsOffset'] : null;
        $this->container['resultsLimit'] = isset($data['resultsLimit']) ? $data['resultsLimit'] : null;
        $this->container['resultsTotalAvailable'] = isset($data['resultsTotalAvailable']) ? $data['resultsTotalAvailable'] : null;
        $this->container['scheduledMessages'] = isset($data['scheduledMessages']) ? $data['scheduledMessages'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['timeStamp'] === null) {
            $invalidProperties[] = "'timeStamp' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['statusCode'] === null) {
            $invalidProperties[] = "'statusCode' can't be null";
        }
        if ($this->container['resultsOffset'] === null) {
            $invalidProperties[] = "'resultsOffset' can't be null";
        }
        if ($this->container['resultsLimit'] === null) {
            $invalidProperties[] = "'resultsLimit' can't be null";
        }
        if ($this->container['resultsTotalAvailable'] === null) {
            $invalidProperties[] = "'resultsTotalAvailable' can't be null";
        }
        if ($this->container['scheduledMessages'] === null) {
            $invalidProperties[] = "'scheduledMessages' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timeStamp
     *
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->container['timeStamp'];
    }

    /**
     * Sets timeStamp
     *
     * @param string $timeStamp The date/time the request was processed, in the format YYYYMMDDhhmmssSSS
     *
     * @return $this
     */
    public function setTimeStamp($timeStamp)
    {
        $this->container['timeStamp'] = $timeStamp;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version The current version of the API of the endpoint that was called
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets statusCode
     *
     * @return int
     */
    public function getStatusCode()
    {
        return $this->container['statusCode'];
    }

    /**
     * Sets statusCode
     *
     * @param int $statusCode The http status code returned - reflected in the body for convenience
     *
     * @return $this
     */
    public function setStatusCode($statusCode)
    {
        $this->container['statusCode'] = $statusCode;

        return $this;
    }

    /**
     * Gets resultsOffset
     *
     * @return int
     */
    public function getResultsOffset()
    {
        return $this->container['resultsOffset'];
    }

    /**
     * Sets resultsOffset
     *
     * @param int $resultsOffset The number of items skipped before the results were returned. This is the value specified in the ***offset*** parameter sent to the endpoint. If the parameter was not specified, this defaults to 0.
     *
     * @return $this
     */
    public function setResultsOffset($resultsOffset)
    {
        $this->container['resultsOffset'] = $resultsOffset;

        return $this;
    }

    /**
     * Gets resultsLimit
     *
     * @return int
     */
    public function getResultsLimit()
    {
        return $this->container['resultsLimit'];
    }

    /**
     * Sets resultsLimit
     *
     * @param int $resultsLimit The number of items returned in the results. This is the value specified in the ***limit*** parameter sent to the endpoint. If the parameter was not specified, this defaults to 100.
     *
     * @return $this
     */
    public function setResultsLimit($resultsLimit)
    {
        $this->container['resultsLimit'] = $resultsLimit;

        return $this;
    }

    /**
     * Gets resultsTotalAvailable
     *
     * @return int
     */
    public function getResultsTotalAvailable()
    {
        return $this->container['resultsTotalAvailable'];
    }

    /**
     * Sets resultsTotalAvailable
     *
     * @param int $resultsTotalAvailable The total number of results available for retrieval. The ***offset*** and ***limit*** properties specify which of the total available results have been returned.
     *
     * @return $this
     */
    public function setResultsTotalAvailable($resultsTotalAvailable)
    {
        $this->container['resultsTotalAvailable'] = $resultsTotalAvailable;

        return $this;
    }

    /**
     * Gets scheduledMessages
     *
     * @return \winsms\Models\ScheduledMessage[]
     */
    public function getScheduledMessages()
    {
        return $this->container['scheduledMessages'];
    }

    /**
     * Sets scheduledMessages
     *
     * @param \winsms\Models\ScheduledMessage[] $scheduledMessages An array of ***scheduledMessage*** objects containing properties of each unsent scheduled message.
     *
     * @return $this
     */
    public function setScheduledMessages($scheduledMessages)
    {
        $this->container['scheduledMessages'] = $scheduledMessages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


